# Generated by Django 3.2 on 2021-05-07 12:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('Boda Boda', 'Boda Boda'), ('Van/Kirikuu', 'Van/Kirikuu'), ('Truck', 'Truck')], max_length=100)),
                ('details', models.TextField()),
                ('service_icon', models.CharField(choices=[('motorcycle', 'motorcycle'), ('shuttle-van', 'shuttle-van'), ('truck-moving', 'truck-moving')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_vehicle', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('package_size', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('booked_on', models.DateTimeField(default=datetime.datetime.now)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
