# Generated by Django 3.1.7 on 2021-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210329_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='icon_label',
            field=models.CharField(choices=[('motorcycle', 'motorcycle'), ('shuttle-van', 'shuttle-van'), ('truck-moving', 'truck-moving')], max_length=20, null=True),
        ),
    ]
