# Generated by Django 3.1.7 on 2021-04-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vehicle_icon_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_from', models.CharField(max_length=200, null=True)),
                ('to', models.CharField(max_length=200, null=True)),
                ('from_Address', models.CharField(max_length=200, null=True)),
                ('to_Address', models.CharField(max_length=200, null=True)),
                ('Region', models.CharField(max_length=200, null=True)),
                ('town', models.CharField(max_length=200, null=True)),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.bookings')),
            ],
            options={
                'verbose_name_plural': 'Cargo information',
            },
        ),
    ]
