# Generated by Django 3.1.7 on 2021-04-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210401_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
