# Generated by Django 3.1.7 on 2021-04-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210401_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoinfo',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
