# Generated by Django 3.1.7 on 2021-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_cargoinfo_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoinfo',
            name='booking',
        ),
        migrations.AddField(
            model_name='cargoinfo',
            name='booking_info_for',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
