# Generated by Django 3.1.7 on 2021-04-01 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_auto_20210401_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
