# Generated by Django 3.1.3 on 2021-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210429_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('motoboy', 'Motoboy'), ('mintruck', 'Min Truck'), ('tuck', 'Truck')], max_length=100)),
                ('details', models.TextField()),
                ('service_icon', models.CharField(choices=[('motorcycle', 'motorcycle'), ('shuttle-van', 'shuttle-van'), ('truck-moving', 'truck-moving')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='cargoinfo',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='cargoinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookedVehicle',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='CargoInfo',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
