# Generated by Django 3.2 on 2021-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210415_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Boda Boda', 'Boda Boda'), ('Van/Kirikuu', 'Van/Kirikuu'), ('Truck', 'Truck')], max_length=20),
        ),
    ]
