# Generated by Django 3.1.3 on 2021-05-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210507_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Boda Boda', 'Boda Boda'), ('Van/Kirikuu', 'Van/Kirikuu'), ('Truck', 'Truck')], max_length=100),
        ),
    ]
