# Generated by Django 3.1.3 on 2021-05-07 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210507_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_vehicle', models.CharField(max_length=100)),
                ('pickup_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('booked_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
