# Generated by Django 3.1.3 on 2021-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_booking_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='package_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
